add test for ts-node

diff --git a/backend/Dockerfile b/backend/Dockerfile
--- a/backend/Dockerfile
+++ b/backend/Dockerfile
@@ -22,10 +22,12 @@ WORKDIR /app
 COPY backend/package*.json ./
 RUN npm install
 
-ENV PATH="/app/node_modules/.bin:$PATH"
 
 COPY backend/ .
 COPY shared/ ./shared/
+ENV PATH="/app/node_modules/.bin:$PATH"
+
+RUN ls /app/node_modules/.bin/ts-node && echo "ts-node found" || echo "ts-node NOT found"
 RUN npx prisma generate --schema=./prisma/schema.prisma
 
 #RUN npm run build
